"""
Django settings for TIH project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# AUTH_USER_MODEL = 'accounts.CustomUser'
# AUTH_USER_MODEL = 'yourapp.CustomUser'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0i3*j%e^_mxm_=@$5$n%jti4_!*z5&12t1jz&a-bfxkn5vzi7q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
AUTH_USER_MODEL = 'accounts.CustomUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'drf_yasg',
    'knox',
    'corsheaders',
    'home'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sampleuser788@gmail.com'
EMAIL_HOST_PASSWORD = 'vcdl vzmt ulbe hobq'

# CORS_ALLOWED_ORIGINS = [
#     "*", http://localhost:3000/ 
#     # Add the origin of your frontend
#     # Add other origins as needed
#   ]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://0.0.0.0",
    "http://0.0.0.0.",
    "http://*",
    "http://localhost:3000"
]

ROOT_URLCONF = 'TIH.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TIH.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Set a session timeout (in seconds). Adjust according to your needs.
# For example, 1209600 seconds is two weeks.
SESSION_COOKIE_AGE = 60

# Set the session cookie name. You can customize it if needed.
# SESSION_COOKIE_NAME = 'your_session_cookie_name'

# DATABASES = {
#     'default':{
#         'ENGINE': 'djongo',
#         'NAME': 'tih',
#         "CLIENT": {
#         'host': 'mongodb://admin:admin_password@13.48.46.173:27017/',
       
#         }
#     }
# }


# DATABASES = {
#     'default':{
#         'ENGINE': 'djongo',
#         'NAME': 'tih',
#     }
# }



import os
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.environ.get("DB_NAME", "django_testing"),
        "USER": os.environ.get("DB_USER", "admin"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "admin"),
        "HOST": os.environ.get("DB_HOST", "mysql"),
        "PORT": os.environ.get("DB_PORT", "3306"),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
# "default": {
#     "ENGINE": "djongo",
#     'ENFORCE_SCHEMA': False,
#     "NAME": "Blog",  # name of your DB which you want to access
#     "CLIENT": {
#         # 'host': 'mongodb+srv://charan:charan19@cluster0.haku4rf.mongodb.net/?retryWrites=true&w=majority',  # your db_url if not hosted then localhost
#         'host': 'mongodb+srv://charan19:Charan%4019@cluster0.sjdixl3.mongodb.net/?retryWrites=true&w=majority',
#         'port': 27017,  # port e.g. 27017
#         'username': 'charan19',
#         'password': 'Charan@19',
#         'authSource': 'admin',  # set your db auth_source if you know
#         'authMechanism': 'SCRAM-SHA-1'  # set your auth_mechanism if you know
# # add other settings as per your requirements
#     }
# }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication',
        # 'knox.auth.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
    # Other settings...
}

MEDIA_URL = '/blogs/'
MEDIA_ROOT = BASE_DIR / "blogs"

