# Generated by Django 4.1.13 on 2023-12-13 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('79ee79c5-b0da-4cdb-a530-9c2f7fea37c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
