# Generated by Django 4.1.13 on 2023-12-15 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('36691d7c-966b-4200-9b28-8d04ed2d6f9f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
