# Generated by Django 4.1.13 on 2024-01-09 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('50c2d34b-adbe-4f13-a2a3-c6204dfebfe8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
