# Generated by Django 4.1.13 on 2024-01-09 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('561fb738-fb9a-4b81-a7b0-0788804ac0f2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
