# Generated by Django 4.1.13 on 2024-01-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_blog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
