# Generated by Django 4.1.13 on 2024-01-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
