# Generated by Django 4.1.13 on 2024-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
