# Generated by Django 4.1.13 on 2024-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_blog_video_blog_votes_alter_blog_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='votes',
        ),
        migrations.AddField(
            model_name='blog',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
