# Generated by Django 4.1.13 on 2024-01-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blog_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
    ]
