# Generated by Django 4.1.13 on 2024-01-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_blog_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='upload_image',
        ),
    ]
