# Generated by Django 4.1.13 on 2024-02-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_image_blog_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
