# Generated by Django 4.1.13 on 2024-02-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='add_comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='add_reply',
        ),
    ]
