# Generated by Django 4.1.13 on 2024-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_blog_text_blog_summary_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
