# Generated by Django 4.1.13 on 2024-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_blog_upvoted_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvotedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='upvoted_users',
        ),
        migrations.AddField(
            model_name='blog',
            name='upvoted_users',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
