# Generated by Django 4.1.13 on 2024-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_upvoteduser_remove_blog_upvoted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dummy_is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
